// Regenerates lib/business-case-context.js from the source markdown documents.
// Runs as "prebuild": if the source .md files are absent (e.g. in CI), the
// existing generated module is kept and the build proceeds.
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outFile = path.join(projectRoot, "lib", "business-case-context.js");

const sources = [
  {
    header: "DOCUMENT 1 — Business case (padel-business-case.md)",
    file: path.resolve(projectRoot, "..", "padel-business-case.md"),
  },
  {
    header: "DOCUMENT 2 — Next steps: contacts and first bets (next-steps-contacts.md)",
    file: path.resolve(projectRoot, "..", "next-steps-contacts.md"),
  },
  {
    header: "DOCUMENT 3 — Strategy note: how we win (strategy-note.md)",
    file: path.resolve(projectRoot, "..", "strategy-note.md"),
  },
];

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

const missing = [];
for (const s of sources) {
  if (!(await exists(s.file))) missing.push(s.file);
}

if (missing.length > 0) {
  if (await exists(outFile)) {
    console.log(
      `generate-context: source markdown not found (${missing.join(", ")}); keeping existing ${path.relative(projectRoot, outFile)}.`,
    );
    process.exit(0);
  }
  console.error(
    `generate-context: source markdown not found (${missing.join(", ")}) and no existing ${path.relative(projectRoot, outFile)} to fall back to.`,
  );
  process.exit(1);
}

const parts = [];
for (const s of sources) {
  const content = (await readFile(s.file, "utf8")).trim();
  parts.push(`===== ${s.header} =====\n\n${content}`);
}
const combined = parts.join("\n\n\n");

const moduleSource = `// Generated by scripts/generate-context.mjs — do not edit by hand.\n// Contains the source documents (business case + next steps + strategy note) with clear headers.\nexport const BUSINESS_CASE = ${JSON.stringify(combined)};\n`;

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, moduleSource, "utf8");
console.log(
  `generate-context: wrote ${path.relative(projectRoot, outFile)} (${combined.length.toLocaleString("en-GB")} chars from ${sources.length} documents).`,
);
